---

- name: add vimbadmin config
  template:
    src: application.ini
    dest: '{{ vimbadmin_root_dir }}/application/configs/application.ini'
    owner: '{{ vimbadmin_user }}'
    group: '{{ vimbadmin_group }}'
    mode: '0400'

- name: Ensure config directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /etc/php5/fpm/pool.d
    - /etc/nginx/conf.d

- name: add php5-fpm config
  template:
    src: php5-fpm.conf
    dest: /etc/php5/fpm/pool.d/system.vimbadmin.conf
  notify: restart php5-fpm

- name: add nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/vimbadmin.conf
  notify: restart nginx

- name: Ensure var folder is writable
  file:
    path: '{{ vimbadmin_root_dir }}/var'
    state: directory
    owner: 'www-data'
    group: '{{ vimbadmin_group }}'
    mode: '0777'
    recurse: true